export const productData = [
    {
        id:1,
        img:"/assets/image/products/product1.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#000",
        colorName:"مشکی",
        size:["sm","l","xl"],
    },
    {
        id:2,
        img:"/assets/image/products/product2.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#e683dd",
        colorName:"صورتی",
        size:["sm","l"],
    },
    {
        id:3,
        img:"/assets/image/products/product3.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#e8e6ab",
        colorName:"کرمی",
        size:["m","xl"],
        
    },
    {
        id:4,
        img:"/assets/image/products/product4.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#7e7e7e",
        colorName:"طوسی",
        size:["m","xl"],

    },
    {
        id:5,
        img:"/assets/image/products/product5.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#991313",
        colorName:"زرشکی",
        size:["l"],
    },
    {
        id:6,
        img:"/assets/image/products/product6.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"red",
        colorName:"قرمز",
        size:["s","m","l","xl"],
    },
    {
        id:7,
        img:"/assets/image/products/product7.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#000",
        colorName:"مشکی",
        size:["s","m","l","xl"],
    },
    {
        id:8,
        img:"/assets/image/products/product8.jpg",
        title:"کاپشن چرمی",
        price:570000,
        color:"#e8e6ab",
        colorName:"کرمی",
        size:["s","m","l","xl"],
    },
]